// Türkiye liman kodları - 649 liman
export interface Port {
  code: string;
  name: string;
}

export const TURKEY_PORTS: Port[] = [
  { code: 'TRALA-001', name: 'ALANYA DEMİR MEVKİİ' },
  { code: 'TRALA-002', name: 'ALANYA İSKELESİ' },
  { code: 'TRALA-003', name: 'AYTEMİZ AKARYAKIT ALANYA DOLUM TESİSİ' },
  { code: 'TRALA-004', name: 'GAZİPAŞA BALIK YÜKLEME DEMİRİ' },
  { code: 'TRALA-005', name: 'ALANYA MARİNA' },
  { code: 'TRALI-001', name: 'ALPET TÜRKİYE A.Ş. ALİAĞA TERMİNALİ' },
  { code: 'TRALI-002', name: 'APM TERMİNALS KONTEYNER TERMİNALİ' },
  { code: 'TRALI-003', name: 'BATILİMAN LİMAN İŞLETMESİ' },
  { code: 'TRALI-004', name: 'EGE ÇELİK LİMANI' },
  { code: 'TRALI-005', name: 'EGE GAZ A.Ş. PLATFORM-İSKELESİ' },
  { code: 'TRALI-006', name: 'EGE GÜBRE LİMAN TESİSİ' },
  { code: 'TRALI-007', name: 'ETKİ LİMANI' },
  { code: 'TRALI-008', name: 'HABAŞ NEMRUT LİMANI' },
  { code: 'TRALI-009', name: 'İDÇ NEMRUT LİMANI' },
  { code: 'TRALI-010', name: 'NEMPORT İSKELESİ' },
  { code: 'TRALI-011', name: 'NEMRUT PLATFORMU' },
  { code: 'TRALI-012', name: 'PETKİM LİMANI' },
  { code: 'TRALI-013', name: 'SOCAR TURKEY AKARYAKIT DEPOLAMA ALİAĞA ŞUBESİ' },
  { code: 'TRALI-014', name: 'GÜZEL ENERJİ AKARYAKIT A.Ş. ALİAĞA TESİSİ' },
  { code: 'TRALI-015', name: 'TÜPRAŞ-ALİAĞA TERMİNALİ' },
  { code: 'TRALI-016', name: 'ALİAĞA GEMİ SÖKÜM BÖLGESİ' },
  { code: 'TRALI-017', name: 'NEMRUT KÖRFEZİ DEMİRLEME SAHASI' },
  { code: 'TRALI-018', name: 'STAR RAFİNERİ LİMAN TESİSİ' },
  { code: 'TRALI-019', name: '1 NOLU DEMİR (AKARYAKIT, ASKERİ TANKER)' },
  { code: 'TRALI-020', name: '2 NOLU DEMİR SAHASI' },
  { code: 'TRALI-021', name: '3 NOLU DEMİR SAHASI (TEHLİKELİ)' },
  { code: 'TRALI-022', name: '4 NOLU DEMİR SAHASI' },
  { code: 'TRALI-023', name: '5 NOLU DEMİR SAHASI' },
  { code: 'TRALI-024', name: '6 NOLU DEMİR SAHASI (TEHLİKELİ)' },
  { code: 'TRALI-025', name: 'GEMİ SÖKÜM DEMİR SAHASI' },
  { code: 'TRALI-026', name: '8 NOLU DEMİR SAHASI (TEHLİKELİ)' },
  { code: 'TRALI-027', name: 'ALIAPORT' },
  { code: 'TRAMA-001', name: 'KURUCAŞİLE BALIKÇI BARINAĞI' },
  { code: 'TRAMA-002', name: 'AKKONAK İSKELESİ' },
  { code: 'TRAMA-003', name: 'AMASRA LİMANI' },
  { code: 'TRAMA-004', name: 'DEMİRLEME SAHASI 1' },
  { code: 'TRAMA-005', name: 'DEMİRLEME SAHASI 2' },
  { code: 'TRAMB-001', name: 'AKÇANSA AMBARLI LİMANI' },
  { code: 'TRAMB-002', name: 'AMBARLI DEPOLAMA VE DOLUM TERMİNALİ' },
  { code: 'TRAMB-003', name: 'AMBARLI LİMAN TESİSLERİ MARDAŞ İSKELESİ' },
  { code: 'TRAMB-004', name: 'AYGAZ A.Ş. AMBARLI TERMİNALİ' },
  { code: 'TRAMB-005', name: 'KUMPORT LİMANI' },
  { code: 'TRAMB-006', name: 'KURUYÜK DEMİR ALANI' },
  { code: 'TRAMB-007', name: 'MARPORT KONTEYNER TERMİNALİ' },
  { code: 'TRAMB-008', name: 'HARAMİDERE TERMİNALİ' },
  { code: 'TRAMB-009', name: 'TEHLİKELİ YÜK DEMİR ALANI' },
  { code: 'TRAMB-010', name: 'WEST İSTANBUL MARİNA' },
  { code: 'TRAMB-011', name: 'AVCILAR İDO TERMİNALİ' },
  { code: 'TRAMB-012', name: 'MİMARSİNAN BALIKÇI BARINAĞI İSKELESİ' },
  { code: 'TRAMB-013', name: 'BÜYÜKÇEKMECE BALIKÇI BARINAĞI' },
  { code: 'TRAMB-014', name: 'GÜZELCE BALIKÇI BARINAĞI' },
  { code: 'TRAMB-015', name: 'AVCILAR BALIKÇI BARINAĞI' },
  { code: 'TRAMB-016', name: 'GÜRPINAR BALIKÇI BARINAĞI' },
  { code: 'TRAMB-017', name: 'KIYI İSTANBUL MARİNA' },
  { code: 'TRANA-001', name: 'DEMİRLEME SAHASI' },
  { code: 'TRANA-002', name: 'FERİBOT VE DENİZ UÇAĞI İSKELESİ' },
  { code: 'TRAYT-001', name: 'AKDENİZ AKARYAKIT DEPOLAMA NAKLİYAT VE TİC. A.Ş.' },
  { code: 'TRAYT-002', name: 'ANTALYA SERBEST BÖLGESİ ASBAŞ LİMANI 11 NOLU RIHTIM (ASBAŞ RIHTIM' },
  { code: 'TRAYT-003', name: 'ÇEKİSAN ANTALYA TERMİNALİ' },
  { code: 'TRAYT-004', name: 'KALEİÇİ YAT LİMANI' },
  { code: 'TRAYT-005', name: 'PETROL OFİSİ A.Ş. ANTALYA TERMİNALİ' },
  { code: 'TRAYT-006', name: 'PORT AKDENİZ ANTALYA LİMANI' },
  { code: 'TRAYT-007', name: 'SHELLTURCAS ANTALYA TERMİNALİ' },
  { code: 'TRAYT-008', name: 'NATO DOLUM TESİSİ' },
  { code: 'TRAYT-009', name: 'ANTALYA SERBEST BÖLGESİ ASBAŞ LİMANI' },
  { code: 'TRAYT-010', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRAYT-011', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRAYT-012', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRAYV-001', name: 'AYVALIK YAT LİMANI' },
  { code: 'TRBDM-001', name: 'BAGFAŞ BANDIRMA LİMANI' },
  { code: 'TRBDM-002', name: 'ÇELEBİ BANDIRMA LİMANI' },
  { code: 'TRBDM-003', name: 'İDO BANDIRMA İSKELESİ' },
  { code: 'TRBDM-004', name: 'İSA BALABAN' },
  { code: 'TRBDM-005', name: 'AE GEMİ VE TERSANECİLİK' },
  { code: 'TRBDM-006', name: 'İLYAS KÖROĞLU (KARDEŞLER DENİZCİLİK)' },
  { code: 'TRBDM-007', name: 'BALABAN KARDEŞLER GEMİ SAN. NAK. GIDA TUR. TİC. LTD. ŞTİ.' },
  { code: 'TRBDM-008', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRBDM-009', name: '2 NOLU DEMİRLEME SAHASI (TEHLİKELİ)' },
  { code: 'TRBDM-010', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRBTN-002', name: 'BARTIN LİMANI' },
  { code: 'TRBTN-003', name: 'BARTIN DEMİR YERİ 1' },
  { code: 'TRBTN-004', name: 'BARTIN DEMİR YERİ 2  (TEHLİKELİ YÜK)' },
  { code: 'TRBXN-001', name: 'BODRUM MİLTA MARİNA' },
  { code: 'TRBXN-002', name: 'BODRUM YOLCU İSKELESİ' },
  { code: 'TRBXN-005', name: 'MUĞLA BÜYÜKŞEHİR BELEDİYESİ BODRUM YAT LİMANI' },
  { code: 'TRBXN-006', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRBXN-007', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRBXN-008', name: 'D-MARİN TURGUTREİS YAT LİMANI' },
  { code: 'TRBXN-009', name: 'PALMARİNA BODRUM MARİNA' },
  { code: 'TRBXN-010', name: 'Ağanlar Tersanesi Tekne İmal ve Çekek Yeri' },
  { code: 'TRBXN-011', name: 'ATM TEKNE İMAL VE ÇEKEK YERİ' },
  { code: 'TRBXN-012', name: 'NETA MARİNA TEKNE İMAL VE ÇEKEK YERİ' },
  { code: 'TRBXN-013', name: 'YAT LİFT ÇEKEK YERİ' },
  { code: 'TRBZC-001', name: 'GÜLPINAR BALIKÇI BARINAĞI' },
  { code: 'TRBZC-002', name: 'GEYİKLİ YÜKYERİ İSKELESİ' },
  { code: 'TRBZC-003', name: '1 NOLU DEMİR SAHASI' },
  { code: 'TRBZC-004', name: '2 NOLU DEMİR SAHASI' },
  { code: 'TRBZC-005', name: '3 NOLU DEMİR SAHASI' },
  { code: 'TRBZC-006', name: 'GESTAŞ BOZCAADA LİMANI' },
  { code: 'TRCES-001', name: 'ALAÇATI YAT LİMANI' },
  { code: 'TRCES-002', name: 'ALTINYUNUS SETUR YAT LİMANI' },
  { code: 'TRCES-003', name: 'ÇEŞME LİMANI SERBEST DEMİR YERİ' },
  { code: 'TRCES-004', name: 'ÇEŞME MARİNA' },
  { code: 'TRCES-005', name: 'DALYAN YAT YANAŞMA YERİ' },
  { code: 'TRCES-006', name: 'ULUSOY ÇEŞME LİMANI' },
  { code: 'TRCES-007', name: 'SIĞACIK YAT LİMANI' },
  { code: 'TRCKZ-0001', name: 'AYVALIK BELEDİYE VAPUR İSKELESİ' },
  { code: 'TRCKZ-001', name: 'ASKERİ POL' },
  { code: 'TRCKZ-002', name: 'ÇANAKKALE AKÇANSA LİMANI' },
  { code: 'TRCKZ-004', name: 'ÇANAKKALE BELEDİYE YAT LİMANI' },
  { code: 'TRCKZ-006', name: 'ÇANAKKALE FERİBOT İSKELESİ' },
  { code: 'TRCKZ-007', name: 'ÇANAKKALE KEPEZ LİMANI' },
  { code: 'TRCKZ-009', name: 'GELİBOLU TERSANESİ' },
  { code: 'TRCKZ-009', name: 'GELİBOLU TERSANESİ' },
  { code: 'TRCKZ-011', name: 'TDİ KABATEPE LİMANI' },
  { code: 'TRCKZ-011', name: 'KABATEPE LİMANI' },
  { code: 'TRCKZ-013', name: 'DÜZKOÇ - FALCON KEPEZ İSKELESİ' },
  { code: 'TRCKZ-014', name: 'ÇANAKKALE BOTAŞ FAALİYET ALANI' },
  { code: 'TRCKZ-015', name: 'KARANLIK LİMAN DEMİR SAHASI' },
  { code: 'TRCKZ-016', name: 'AKÇANSA DEMİR SAHASI' },
  { code: 'TRCKZ-017', name: 'ŞEVKETİYE DEMİR SAHASI' },
  { code: 'TRDAT-001', name: 'DATÇA KÖRMEN YAT LİMANI' },
  { code: 'TRDAT-002', name: 'MERKEZ BALIKÇI BARINAĞI' },
  { code: 'TRDAT-003', name: 'KÖRMEN BALIKÇI BARINAĞI' },
  { code: 'TRDAT-004', name: 'PALAMUTBÜKÜ BALIKÇI BARINAĞI' },
  { code: 'TRDAT-005', name: 'MESUDİYE BALIKÇI BARINAĞI' },
  { code: 'TRDAT-006', name: '2 NOLU DEMİR SAHASI' },
  { code: 'TRDAT-007', name: '1 NOLU DEMİR SAHASI' },
  { code: 'TRDAT-008', name: 'KAIROS YOLCU LİMANI' },
  { code: 'TRDIK-001', name: 'DİKİLİ LİMANI' },
  { code: 'TRDIK-002', name: 'DİKİLİ DEMİRLEME SAHASI' },
  { code: 'TREDO-001', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TREDO-002', name: 'KÜÇÜKKUYU BALIKÇI BARINAĞI' },
  { code: 'TREDO-003', name: 'ALTINOLUK BALIKCI BARINAĞI' },
  { code: 'TREDO-004', name: 'AKÇAY İSKELESİ' },
  { code: 'TREDO-005', name: 'GESTAŞ KÜÇÜKKUYU YANAŞMA YERİ' },
  { code: 'TREDO-006', name: 'BABAKALE BALIKCI BARINAĞI' },
  { code: 'TREDO-007', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRENE-001', name: 'BOTAŞ SAROS FSRU TERMİNALİ' },
  { code: 'TRENE-002', name: 'BOTAŞ SAROS DEMİRLEME SAHASI' },
  { code: 'TRERE-001', name: 'ERDEMİR LİMANI' },
  { code: 'TRERE-002', name: 'KARADENİZ EREĞLİ  BOZHANE LİMANI' },
  { code: 'TRERE-003', name: 'ASKERİ LİMAN' },
  { code: 'TRERE-004', name: 'TERSANELER TEÇHİZ LİMAN' },
  { code: 'TRERE-005', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRERE-006', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRERE-007', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRERE-008', name: '4 NOLU DEMİRLEME SAHASI' },
  { code: 'TRERE-009', name: 'MADENCİ GEMİ TERSANESİ' },
  { code: 'TRERE-010', name: 'USTAMEHMETOĞLU GEMİ TERSANESİ' },
  { code: 'TRERE-011', name: 'USTAOĞLU GEMİ TERSANESİ' },
  { code: 'TRERE-012', name: 'EREĞLİ GEMİ TERSANESİ' },
  { code: 'TRERK-001', name: 'FERİ İSKELESİ' },
  { code: 'TRERK-002', name: 'ANT TESİSLERİ' },
  { code: 'TRERK-003', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRERK-004', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRFAS-001', name: 'FATSA BALIKÇI BARINAĞI' },
  { code: 'TRFAS-002', name: 'FATSA İSKELESİ' },
  { code: 'TRFAS-003', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRFAS-004', name: '2 NOLU DEMİRLEME SAHASI (TEHLİKELİ)' },
  { code: 'TRFET-001', name: 'ECE MARİNA YAT LİMANI' },
  { code: 'TRFET-002', name: 'FETHİYE BELEDİYE İSKELESİ' },
  { code: 'TRFET-003', name: 'BU-BA INVEST MARİNA' },
  { code: 'TRFET-004', name: '1 NOLU DEMİR SAHASI' },
  { code: 'TRFET-005', name: '2 NOLU DEMİR SAHASI' },
  { code: 'TRFET-006', name: '3 NOLU DEMİR SAHASI' },
  { code: 'TRFIN-001', name: 'FİNİKE BARINMA YERİ VE TURİZM YAT LİMANI  ( BALIKÇI TEKNELERİ HİZ' },
  { code: 'TRFIN-002', name: 'FİNİKE TURİZM YAT LİMANI' },
  { code: 'TRFIN-003', name: 'ÇAYAĞZI DEMİR MEVKİİ' },
  { code: 'TRFIN-004', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRFIN-005', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRFIN-006', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRFOC-001', name: 'ESKİ FOÇA BALIKÇI BARINAĞI' },
  { code: 'TRFOC-002', name: 'FOÇA BELEDİYE RIHTIMLARI' },
  { code: 'TRFOC-003', name: 'OASİS MARİNE YENİ FOÇA' },
  { code: 'TRGCA-001', name: 'KALEKÖY BALIKÇI BARINAĞI' },
  { code: 'TRGCK-001', name: 'CLUP MARİNA' },
  { code: 'TRGCK-002', name: 'D-MARİN GÖCEK MARİNA' },
  { code: 'TRGCK-003', name: 'MARINTÜRK VILLAGE PORT GÖCEK' },
  { code: 'TRGCK-004', name: 'MARİNTÜRK EXCLUSIVE GÖCEK' },
  { code: 'TRGCK-005', name: 'POAŞ DALAMAN TERMİNALİ' },
  { code: 'TRGCK-006', name: 'MY MARİNA' },
  { code: 'TRGCK-007', name: 'SKOPEA MARİNA' },
  { code: 'TRGCK-008', name: 'BELEDİYE YAT YANAŞMA YERİ' },
  { code: 'TRGCK-009', name: '3 NOLU DEMİR SAHASI' },
  { code: 'TRGCK-010', name: '2 NOLU DEMİR SAHASI' },
  { code: 'TRGCK-011', name: '1 NOLU DEMİR SAHASI' },
  { code: 'TRGCK-012', name: '4 NOLU DEMİR SAHASI' },
  { code: 'TRGCK-013', name: 'EKİNCİK KOYU GEÇİCİ DEMİR YERİ' },
  { code: 'TRGCK-014', name: 'PORT AZURE' },
  { code: 'TRGEL-001', name: 'SAROS KÖRFEZİ NATO TESİSİ' },
  { code: 'TRGEM-001', name: 'BORUSAN LİMANI' },
  { code: 'TRGEM-002', name: 'BP GEMLİK TERMİNALİ' },
  { code: 'TRGEM-003', name: 'BURULAŞ GEMLİK İSKELESİ' },
  { code: 'TRGEM-004', name: 'ÇINAR TERSANECİLİK SAN. VE TİC. LTD. ŞTİ.' },
  { code: 'TRGEM-005', name: 'GEMLİK KÜÇÜKKUMLA İSKELESİ' },
  { code: 'TRGEM-006', name: 'GEMPORT GEMLİK LİMAN TESİSİ' },
  { code: 'TRGEM-007', name: 'MKS MARMARA BORU HATTI VE ŞAMANDIRA SİSTEMİ (GEMLİK)' },
  { code: 'TRGEM-008', name: 'RODA GEMLİK LİMANI' },
  { code: 'TRGEM-009', name: 'FISTIKLI KÖYÜ BALIKÇI BARINAĞI' },
  { code: 'TRGEM-010', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRGEM-011', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRGIR-001', name: 'GİRESUN LİMANI' },
  { code: 'TRGIR-002', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRGIR-003', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRGIR-004', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRGIR-005', name: '4 NOLU DEMİRLEME SAHASI' },
  { code: 'TRGOR-001', name: 'GÖRELE BALIKÇI BARINAĞI' },
  { code: 'TRGUL-002', name: 'EGESU GÜLLÜK MARİNA' },
  { code: 'TRGUL-003', name: 'GÜLLÜK MANDALYA LİMANI' },
  { code: 'TRGUL-004', name: 'KILIÇ DENİZ ÜRÜNLERİ İSKELESİ' },
  { code: 'TRGUL-005', name: 'MANDALYA MARİNA' },
  { code: 'TRGUL-007', name: 'GÖKOVA ÖREN MARİNA' },
  { code: 'TRGUL-008', name: '1 NOLU DEMİR SAHASI' },
  { code: 'TRGUL-009', name: '2 NOLU DEMİR SAHASI' },
  { code: 'TRGUL-010', name: 'TERSAN TERSANECİLİK YAT TEKNE İMAL VE ÇEKEK YERİ' },
  { code: 'TRGUL-011', name: 'UFUK DENİZCİLİK YAT ÇEKEK YERİ' },
  { code: 'TRGUL-012', name: 'ÇAVUŞLU TERSANESİ' },
  { code: 'TRHOP-001', name: 'HOPA LİMANI' },
  { code: 'TRHOP-002', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRHOP-003', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRHOP-004', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRIGN-001', name: 'KIYIKÖY BALIKÇI BARINAĞI' },
  { code: 'TRIGN-002', name: '1 NOLU DEMİR YERİ' },
  { code: 'TRIGN-003', name: '2 NOLU DEMİR YERİ' },
  { code: 'TRIGN-004', name: '3 NOLU DEMİR YERİ' },
  { code: 'TRIGN-005', name: 'İĞNEADA BALIKÇI BARINAĞI' },
  { code: 'TRINE-001', name: 'İNEBOLU LİMANI' },
  { code: 'TRINE-002', name: 'İNEBOLU LİMANI DEMİR SAHASI' },
  { code: 'TRINE-003', name: 'TEH.MAD.TAŞI.GEMİ DEMİR SAHASI' },
  { code: 'TRISK-001', name: 'ASSAN PORT İSKENDERUN' },
  { code: 'TRISK-002', name: 'ATAKAŞ LİMAN TESİSİ' },
  { code: 'TRISK-003', name: 'AYGAZ A.Ş. DÖRTYOL TERMİNALİ' },
  { code: 'TRISK-005', name: 'BOTAŞ DÖRTYOL LİMANI' },
  { code: 'TRISK-007', name: 'ÇEVLİK BALIKÇI BARINAĞI' },
  { code: 'TRISK-008', name: 'EKİNCİLER İSKELESİ' },
  { code: 'TRISK-009', name: 'GÜBRETAŞ İSKENDERUN LİMANI' },
  { code: 'TRISK-010', name: 'İPRAGAZ A.Ş. DÖRTYOL STOKLAMA TERMİNALİ' },
  { code: 'TRISK-011', name: 'İSDEMİR LİMANI' },
  { code: 'TRISK-013', name: 'İSKENDERUN BALIKÇI BARINAĞI' },
  { code: 'TRISK-014', name: 'İSKENDERUN KARAYOLLARI ASFALT İSKELESİ' },
  { code: 'TRISK-015', name: 'İSKENDERUN NATO ŞAMANDIRALARI' },
  { code: 'TRISK-016', name: 'LİMAKPORT İSKENDERUN LİMANI' },
  { code: 'TRISK-017', name: 'MİLANGAZ A.Ş. DÖRTYOL TERMİNALİ' },
  { code: 'TRISK-018', name: 'MMK METALURJİ İSKELESİ' },
  { code: 'TRISK-019', name: 'PET GAZ A.Ş. LPG DEPOLAMA VE TÜP DOLUM TESİSİ' },
  { code: 'TRISK-020', name: 'PETROL OFİSİ A.Ş. İSKENDERUN TERMİNALİ' },
  { code: 'TRISK-021', name: 'GLOBAL TERMİNAL HİZMETLERİ' },
  { code: 'TRISK-023', name: 'SARISEKİ NATO İSKELESİ' },
  { code: 'TRISK-024', name: 'SASA İSKENDERUN TANK SAHASI VE DOLUM TESİSİ TERMİNALİ' },
  { code: 'TRISK-027', name: 'YAZICILAR İSKELESİ' },
  { code: 'TRISK-028', name: 'BYPORT PETROL TERMİNALİ' },
  { code: 'TRISK-029', name: 'TOSYALI LİMANI' },
  { code: 'TRISK-031', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRISK-032', name: '2 NOLU DEMİRLEME SAHASI (TEHLİKELİ YÜK)' },
  { code: 'TRISK-033', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRISK-034', name: '4 NOLU DEMİRLEME SAHASI' },
  { code: 'TRISK-035', name: '5-A DEMİRLEME SAHASI (LPG)' },
  { code: 'TRISK-036', name: '5-B DEMİRLEME SAHASI (LNG)' },
  { code: 'TRISK-037', name: '6 NOLU DEMİRLEME SAHASI' },
  { code: 'TRISK-038', name: '7 NOLU DEMİRLEME SAHASI (TEHLİKELİ YÜK)' },
  { code: 'TRISK-039', name: 'HATAY DENİZ OTOBÜSÜ İSKELESİ' },
  { code: 'TRISK-040', name: 'GÜNEY WİMBA DOLUM VE DEPOLAMA TERMİNALİ' },
  { code: 'TRIST-001', name: 'AHIRKAPI DEMİR MEVKİİ' },
  { code: 'TRIST-002', name: 'ATAKÖY MARİNA' },
  { code: 'TRIST-003', name: 'İSPARK İSTİNYE TEKNE PARK' },
  { code: 'TRIST-004', name: 'İSPARK TARABYA TEKNE PARK' },
  { code: 'TRIST-005', name: 'KARAKÖY SALIPAZARI LİMANI' },
  { code: 'TRIST-006', name: 'TDİ SARAYBURNU RIHTIMI' },
  { code: 'TRIST-007', name: 'TCDD HAYDARPAŞA LİMANI' },
  { code: 'TRIST-008', name: 'THY OPET YEŞİLKÖY TERMİNALİ' },
  { code: 'TRIST-009', name: 'ZEYPORT LİMANI' },
  { code: 'TRIST-010', name: 'TDİ KURUÇEŞME RIHTIMI' },
  { code: 'TRIST-011', name: 'BOSTANCI İDO TERMİNALİ' },
  { code: 'TRIST-012', name: 'YENİKAPI İDO TERMİNALİ' },
  { code: 'TRIST-013', name: 'İSTANBUL YENİ HAVA LİMANI AKARYAKIT İKMAL TERMİNALİ' },
  { code: 'TRIST-014', name: 'BAKIRKÖY İDO TERMİNALİ' },
  { code: 'TRIST-015', name: 'MALTEPE İDO TERMİNALİ' },
  { code: 'TRIST-016', name: 'TÜRKELİ DEMİR MEVKİİ' },
  { code: 'TRIST-017', name: 'HALİÇ TERSANESİ' },
  { code: 'TRIZM-001', name: 'ALSANCAK LİMANI' },
  { code: 'TRIZM-002', name: 'DEMİR VE TCDD İZMİR ALS.LİMANI' },
  { code: 'TRIZM-003', name: 'LEVENT MARİNA' },
  { code: 'TRIZT-001', name: 'ADMARİN TERSANESİ' },
  { code: 'TRIZT-002', name: 'AKTAŞ TANK TERMİNALİ' },
  { code: 'TRIZT-003', name: 'ALTINOVA TERSANESİ' },
  { code: 'TRIZT-004', name: 'ALTINTAŞ TERSANECİLİK' },
  { code: 'TRIZT-005', name: 'ALTINTEL LİMAN VE TERMİNALİ' },
  { code: 'TRIZT-006', name: 'ASLAN ÇİMENTO LİMANI' },
  { code: 'TRIZT-007', name: 'AUTOPORT LİMANI' },
  { code: 'TRIZT-008', name: 'BAYRAMOĞLU İSKELESİ' },
  { code: 'TRIZT-009', name: 'BELDEPORT' },
  { code: 'TRIZT-010', name: 'BEŞİKTAŞ TERSANESİ' },
  { code: 'TRIZT-011', name: 'CEMRE TERSANESİ' },
  { code: 'TRIZT-012', name: 'ÇAYIROVA CAM SANAYİ İSKELESİ' },
  { code: 'TRIZT-013', name: 'ÇOLAKOĞLU METALURJİ LİMAN TESİSİ' },
  { code: 'TRIZT-014', name: 'DİLER DEMİR ÇELİK ENDÜSTRİ VE TİC. A.Ş. LİMANI' },
  { code: 'TRIZT-015', name: 'DP WORLD YARIMCA KONTEYNER TERMİNALİ' },
  { code: 'TRIZT-016', name: 'DÜZGİT TERSANESİ' },
  { code: 'TRIZT-017', name: 'AK YAHCT YATÇILIK SAN. TİC. A.Ş.' },
  { code: 'TRIZT-018', name: 'EFESANPORT LİMAN TESİSİ' },
  { code: 'TRIZT-019', name: 'ESKİHİSAR DEMİR' },
  { code: 'TRIZT-020', name: 'EVYAPPORT KİRAZLIYALI LİMANI' },
  { code: 'TRIZT-021', name: 'FORD OTOSAN YENİKÖY İSKELESİ' },
  { code: 'TRIZT-022', name: 'GÜBRETAŞ YARIMCA LİMANI' },
  { code: 'TRIZT-023', name: 'HABAŞ TÜTÜNÇİFTLİK PLATFORMU' },
  { code: 'TRIZT-024', name: 'HATSAN TERSANESİ' },
  { code: 'TRIZT-025', name: 'İGSAŞ LİMANI' },
  { code: 'TRIZT-026', name: 'İZMİT DEMİR' },
  { code: 'TRIZT-027', name: 'KOCATEPE TERSANESİ' },
  { code: 'TRIZT-028', name: 'KORUMA KLOR İSKELESİ' },
  { code: 'TRIZT-029', name: 'KROMAN ÇELİK A.Ş. LİMAN TESİSLERİ' },
  { code: 'TRIZT-030', name: 'KURBAN TERSANESİ' },
  { code: 'TRIZT-031', name: 'LİMAŞ LİMANI' },
  { code: 'TRIZT-032', name: 'MİLANGAZ DOLUM TESİSİ' },
  { code: 'TRIZT-033', name: 'NACİ SELİMOĞLU TERSANESİ' },
  { code: 'TRIZT-034', name: 'NORTHSTAR+E171:E213 TERSANESİ' },
  { code: 'TRIZT-035', name: 'NUH ÇİMENTO SANAYİ A.Ş. LİMAN TESİSİ' },
  { code: 'TRIZT-036', name: 'OP-AY PLATFORM İSKELE' },
  { code: 'TRIZT-037', name: 'ÖZATA TERSANESİ' },
  { code: 'TRIZT-038', name: 'PETLİNE PLATFORMU VE BORU HATTI' },
  { code: 'TRIZT-039', name: 'PETROL OFİSİ A.Ş. DERİNCE TERMİNALİ' },
  { code: 'TRIZT-040', name: 'POLİPORT LİMANI' },
  { code: 'TRIZT-041', name: 'ROTA LİMANI' },
  { code: 'TRIZT-042', name: 'SAFİ DERİNCE LİMANI' },
  { code: 'TRIZT-043', name: 'SEFİNE TERSANESİ' },
  { code: 'TRIZT-044', name: 'SHELL DERİNCE TERMİNALİ' },
  { code: 'TRIZT-045', name: 'ÇİMTAŞ GEMİ İNŞAA' },
  { code: 'TRIZT-046', name: 'SOLVENTAŞ TEKNİK DEPOLAMA A.Ş.' },
  { code: 'TRIZT-047', name: 'TOTAL OİL TÜRKİYE DOLFEN TESİSİ' },
  { code: 'TRIZT-048', name: 'TURKUAZ- İZGİN TERMİNALİ' },
  { code: 'TRIZT-049', name: 'TÜPRAŞ İZMİT RAFİNERİSİ LİMANI' },
  { code: 'TRIZT-050', name: 'TÜRKOĞLU TERSANESİ' },
  { code: 'TRIZT-051', name: 'ATLAS TERSANESİ' },
  { code: 'TRIZT-052', name: 'UZMAR TERSANESİ' },
  { code: 'TRIZT-053', name: 'YARIMCA DEMİR' },
  { code: 'TRIZT-054', name: 'YAŞARSAN TERSANESİ' },
  { code: 'TRIZT-055', name: 'YATCHLEY GEMİ YAPIM' },
  { code: 'TRIZT-056', name: 'YILPORT KONTEYNER TERMİNALİ VE LİMANI' },
  { code: 'TRIZT-057', name: 'İDO ESKİHİSAR İSKELESİ' },
  { code: 'TRIZT-058', name: 'HEREKE KURUYÜK DEMİR YERİ' },
  { code: 'TRIZT-059', name: 'HEREKE SIVIYÜK DEMİR YERİ' },
  { code: 'TRIZT-060', name: 'YILDIZ ENTEGRE LİMAN TESİSİ' },
  { code: 'TRIZT-062', name: 'PORT YARIMCA' },
  { code: 'TRIZT-063', name: 'TURQUOISE SHIPYARD YAT VE GEMİ SAN. A.Ş.' },
  { code: 'TRIZT-064', name: 'NORSE TERSANECİLİK SAN.TİC.A.Ş.' },
  { code: 'TRIZT-065', name: 'UM TERSANESİ' },
  { code: 'TRIZT-066', name: 'VEGA YATÇILIK (SERBEST BÖLGE)' },
  { code: 'TRKAS-001', name: 'KAŞ YAT LİMANI' },
  { code: 'TRKAS-002', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRKAS-003', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRKAS-004', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRKAS-005', name: '4 NOLU DEMİRLEME SAHASI (Demre)' },
  { code: 'TRKMR-001', name: 'DEMİRLEME SAHASI 1' },
  { code: 'TRKMR-002', name: 'DEMİRLEME SAHASI 2' },
  { code: 'TRKMR-003', name: 'DEMİRLEME SAHASI 3 (TEHLİKELİ YÜK)' },
  { code: 'TRKRB-001', name: 'CENAL KARABİGA İSKELESİ' },
  { code: 'TRKRB-0010', name: 'İÇDAŞ TERSANE (TEÇHİZ RIHTIMI)' },
  { code: 'TRKRB-002', name: 'İÇDAŞ-1 (DEĞİRMENCİK)' },
  { code: 'TRKRB-003', name: 'İÇDAŞ-2 (BEKİRLİ)' },
  { code: 'TRKRB-004', name: 'KARABİGA BELEDİYE LİMANI' },
  { code: 'TRKRB-006', name: 'İÇDAŞ TERSANE (KURU HAVUZ)' },
  { code: 'TRKRB-007', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRKRB-008', name: '2 NOLU (TEHLİKELİ) DEMİRLEME SAHASI' },
  { code: 'TRKRB-009', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRKRT-001', name: '1 NOLU DEMİR SAHASI' },
  { code: 'TRKRT-002', name: '2 NOLU DEMİR SAHASI' },
  { code: 'TRKUS-001', name: 'KUŞADASI YOLCU LİMANI' },
  { code: 'TRKUS-002', name: 'D-MARİN DİDİM MARİNA' },
  { code: 'TRKUS-003', name: 'SETUR KUŞADASI MARİNA' },
  { code: 'TRKUS-004', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRKUS-005', name: '2 NOLU DEMİRLEME SAHASI (TEHLİKELİ YÜK)' },
  { code: 'TRMER-001', name: 'AKPET AKARYAKIT MERSİN TERMİNALİ' },
  { code: 'TRMER-002', name: 'ALPET MERSİN DOLUM TESİSİ' },
  { code: 'TRMER-003', name: 'ATAŞ MERSİN TERMİNALİ' },
  { code: 'TRMER-004', name: 'LİMAN DIŞI DEMİR' },
  { code: 'TRMER-005', name: 'LİMAN İÇİ DEMİR' },
  { code: 'TRMER-006', name: 'MERSİN SERBEST BÖLGE RIHTIMI' },
  { code: 'TRMER-007', name: 'MIP MERSİN LİMANI' },
  { code: 'TRMER-008', name: 'NERGİS MERSİN TERMİNALİ' },
  { code: 'TRMER-009', name: 'OPET MERSİN TERMİNALİ' },
  { code: 'TRMER-010', name: 'PETROL OFİSİ A.Ş.  MERSİN TERMİNALİ' },
  { code: 'TRMER-011', name: 'ENERJİ MERSİN TERMİNALİ' },
  { code: 'TRMER-012', name: 'MERSİN KUMKUYU YAT LİMANI' },
  { code: 'TRMER-013', name: 'SAVKA MERSİN TERMİNALİ' },
  { code: 'TRMER-014', name: 'EUROİL KAZANLI MERSİN TERMİNALİ' },
  { code: 'TRMER-015', name: 'TURKİS ENERJİ MERSİN TERMİNALİ' },
  { code: 'TRMRA-001', name: 'MARMARA ADASI ERS İSKELESİ' },
  { code: 'TRMRA-002', name: 'SARAYLAR BELEDİYE LİMANI' },
  { code: 'TRMRA-003', name: 'YAYLA MOZAİK İSKELESİ' },
  { code: 'TRMRA-004', name: 'TUNA MADENCİLİK İSKELESİ' },
  { code: 'TRMRA-005', name: 'MARMARA ADASI İSKELESİ' },
  { code: 'TRMRA-006', name: 'AVŞA İSKELESİ' },
  { code: 'TRMRA-007', name: 'PAŞALİMANI İSKELESİ' },
  { code: 'TRMRA-008', name: 'EKİNLİK İSKELESİ' },
  { code: 'TRMRA-009', name: 'ÇINARLI İSKELESİ' },
  { code: 'TRMRA-010', name: 'BADALAN RIHTIMI (Marmara Birleşik Madencilik)' },
  { code: 'TRMRA-011', name: '1 NOLU SARAYLAR DEMİRLEME SAHASI' },
  { code: 'TRMRA-012', name: '2 NOLU GÜNDOĞDU DEMİRLEME SAHASI' },
  { code: 'TRMRM-001', name: 'MY MARİNA YAT YANAŞMA YERİ' },
  { code: 'TRMRM-002', name: 'ALBATROS MARİNA' },
  { code: 'TRMRM-003', name: 'MARTI MARINA' },
  { code: 'TRMRM-004', name: 'MARMARİS LİMANI' },
  { code: 'TRMRM-005', name: 'NETSEL MARMARİS MARİNA' },
  { code: 'TRMRM-006', name: 'MARMARİS ADAKÖY MARİNA' },
  { code: 'TRMRM-007', name: 'EGESU MARİNA (PORT İASOS)' },
  { code: 'TRMRM-008', name: 'AKSAZ' },
  { code: 'TRMRM-009', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRMRM-010', name: '2 NOLU DEMİRLEME SAHASI (ASKERİ)' },
  { code: 'TRMUD-001', name: 'BURULAŞ MUDANYA İSKELESİ' },
  { code: 'TRMUD-002', name: 'İDO GÜZELYALI İSKELESİ' },
  { code: 'TRORD-001', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRORD-002', name: '2 NOLU (TEHLİKELİ MADDE) DEMİRLEME SAHASI' },
  { code: 'TRORD-003', name: '3 NOLU (UZUN SÜRELİ) DEMİRLEME SAHASI' },
  { code: 'TRRIZ-001', name: 'ÇAYELİ LİMANI' },
  { code: 'TRRIZ-002', name: 'RİZE LİMANI' },
  { code: 'TRRIZ-003', name: 'RİZE LİMANI DEMİR SAHASI' },
  { code: 'TRSIC-001', name: 'SİNOP LİMANI DEMİR SAHASI' },
  { code: 'TRSIC-002', name: 'SİNOP LİMANI' },
  { code: 'TRSIL-001', name: 'DEMİRLEME SAHASI' },
  { code: 'TRSSX-001', name: 'ALTINBAŞ PETROL VE TİCARET A.Ş. (ALPET) DOLUM TESİSİ' },
  { code: 'TRSSX-002', name: 'AYGAZ SAMSUN TERMİNALİ' },
  { code: 'TRSSX-003', name: 'LİKİTGAZ SAMSUN DOLUM VE DEPOLAMA TERMİNALİ' },
  { code: 'TRSSX-004', name: 'PETROL OFİSİ A.Ş. SAMSUN TERMİNALİ' },
  { code: 'TRSSX-005', name: 'SAMSUNPORT' },
  { code: 'TRSSX-006', name: 'TOROS TARIM SAMSUN LİMANI' },
  { code: 'TRSSX-007', name: 'AKPET AKARYAKIT SAMSUN TERMİNALİ' },
  { code: 'TRSSX-008', name: 'SADAŞ SAMSUN TERMİNALİ' },
  { code: 'TRSSX-009', name: 'YEŞİLYURT LİMANI' },
  { code: 'TRSSX-010', name: 'YAKAKENT BALIKÇI BARINAĞI' },
  { code: 'TRSSX-011', name: 'DEREKÖY BALIKÇI BARINAĞI' },
  { code: 'TRSSX-012', name: 'BELEDİYE EVLERİ BALIKÇI BARINAĞI' },
  { code: 'TRSSX-013', name: 'LİMAN İÇİ DEMİR MEVKİİ' },
  { code: 'TRSSX-014', name: 'ETİ BAKIR KIYI TESİSİ' },
  { code: 'TRSSX-015', name: 'TERME TERSANESİ' },
  { code: 'TRSSX-016', name: '1 NOLU DEMİR SAHASI (LİMAN İÇİ 1000 GRT KÜÇÜK)' },
  { code: 'TRSSX-017', name: '2 NOLU DEMİR SAHASI (5000 GRT KÜÇÜK)' },
  { code: 'TRSSX-018', name: '3 NOLU DEMİR SAHASI (+5000 GRT)' },
  { code: 'TRSSX-019', name: '4 NOLU DEMİR SAHASI (TEHLİKELİ YÜK)' },
  { code: 'TRSSX-020', name: 'MBT KİMYA SAMSUN LİMANI' },
  { code: 'TRSUR-001', name: 'YENİÇAM TERSANE RIHTIMI' },
  { code: 'TRSUR-002', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRSUR-003', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRSUR-004', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRSUR-005', name: '4 NOLU DEMİRLEME SAHASI' },
  { code: 'TRSUR-006', name: '5 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTAS-001', name: 'YEŞİLOVACIK LİMANI TAŞUCU' },
  { code: 'TRTAS-002', name: 'TAŞUCU BALIKÇI BARINAĞI, FERİBOT VE YAT YANAŞMA İSKELESİ' },
  { code: 'TRTAS-003', name: 'CEYPORT TAŞUCU ULUSLARARASI LİMAN İŞL.A.Ş.' },
  { code: 'TRTAS-004', name: 'AĞALAR LİMANI NATO İSKELESİ' },
  { code: 'TRTAS-005', name: 'KILIÇ DENİZ ÜRÜNLERİ BALIK ÇİFTLİĞİ' },
  { code: 'TRTAS-006', name: 'YEŞİLOVACIK BALIKÇI BARINAĞI' },
  { code: 'TRTAS-007', name: 'AKKUYU DOĞU KARGO TERMİNALİ' },
  { code: 'TRTAS-008', name: '1 NOLU DEMİR SAHASI' },
  { code: 'TRTAS-009', name: '2 NOLU DEMİR SAHASI(TEHLİKELİ MADDE)' },
  { code: 'TRTAS-010', name: 'YEŞİLOVACIK LİMANI DEMİRLEME SAHASI' },
  { code: 'TRTEK-001', name: 'ARGAZ LPG DEPOLAMA TESİSİ' },
  { code: 'TRTEK-002', name: 'ASYAPORT' },
  { code: 'TRTEK-003', name: 'BOTAŞ LNG TERMİNALİ İSKELESİ' },
  { code: 'TRTEK-004', name: 'BÜTANGAZ TRAKYA DEPOLAMA TERMİNALİ' },
  { code: 'TRTEK-005', name: 'MARMARA DEPOCULUK HİZ. A.Ş. BORU HATTI DOLFEN SİSTEMİ' },
  { code: 'TRTEK-006', name: 'MARTAŞ MARMARA EREĞLİSİ LİMAN TESİSİ' },
  { code: 'TRTEK-007', name: 'LİKİTGAZ MARMARA EREĞLİSİ DEPOLAMA VE DOLUM TERMİNALİ' },
  { code: 'TRTEK-008', name: 'OPET PETROLCÜLÜK A.Ş. MARMARA TERMİNALİ' },
  { code: 'TRTEK-009', name: 'TDİ TEKİRDAĞ LİMANI' },
  { code: 'TRTEK-010', name: 'TMO GENEL MÜDÜRLÜĞÜ TEKİRDAĞ İSKELESİ' },
  { code: 'TRTEK-011', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTEK-012', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTEK-013', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTEK-014', name: '4 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTEK-015', name: '5 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTEK-016', name: '6 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTEK-017', name: '7 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTEK-018', name: 'ŞARKÖY BALIKÇI BARINAĞI' },
  { code: 'TRTEK-019', name: 'MÜREFTE BALIKÇI BARINAĞI' },
  { code: 'TRTEK-020', name: 'HOŞKÖY BALIKÇI BARINAĞI' },
  { code: 'TRTEK-021', name: 'KUMBAĞ  BALIKÇI BARINAĞI' },
  { code: 'TRTEK-022', name: 'BARBAROS BALIKÇI BARINAĞI' },
  { code: 'TRTEK-023', name: 'TEKİRDAĞ BALIKÇI BARINAĞI' },
  { code: 'TRTEK-024', name: 'MARMARA EREĞLİSİ BALIKÇI BARINAĞI' },
  { code: 'TRTEK-025', name: 'BOTAŞ FAALİYET ALANI' },
  { code: 'TRTEK-026', name: 'LİKİTPORT TERMİNALİ' },
  { code: 'TRTIR-001', name: 'TİREBOLU BALIKÇI BARINAĞI' },
  { code: 'TRTIR-002', name: 'KARADENİZ LPG TERMİNALİ' },
  { code: 'TRTIR-003', name: 'OPET ESPİYE TERMİNALİ' },
  { code: 'TRTIR-004', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTIR-005', name: '2 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTIR-006', name: '3 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTZX-001', name: 'POAŞ TRABZON TERMİNALİ' },
  { code: 'TRTZX-002', name: 'TRABZON LİMANI' },
  { code: 'TRTZX-003', name: 'AYTEMİZ TRABZON TERMİNALİ' },
  { code: 'TRTZX-005', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRTZX-006', name: '2 NOLU DEMİRLEME SAHASI (TEHLİKELİ YÜK)' },
  { code: 'TRTZX-007', name: '3 NOLU DEMİRLEME SAHASI (UZUN SÜRE)' },
  { code: 'TRUNY-001', name: 'ÜNYE LİMANI' },
  { code: 'TRUNY-002', name: '1 NOLU DEMİRLEME SAHASI' },
  { code: 'TRUNY-003', name: '2 NOLU DEMİRLEME SAHASI (TEHLİKELİ)' },
  { code: 'TRUNY-004', name: 'ÜNYE TERSANESİ' },
  { code: 'TRYAL-001', name: 'YALOVA RO-RO TERMİNALİ' },
  { code: 'TRYAL-002', name: 'ETERPARK YALOVA TERMİNALİ' },
  { code: 'TRYAL-003', name: 'SETUR YALOVA YAT LİMANI' },
  { code: 'TRYAL-004', name: 'AKSA AKRİLİK LİMANI' },
  { code: 'TRYAL-005', name: 'TAVŞANLI BELEDİYE İSKELESİ' },
  { code: 'TRYAL-006', name: 'ÖZATA TERSANESİ' },
  { code: 'TRYAL-007', name: 'SANMAR DENİZCİLİK TERSANESİ' },
  { code: 'TRYAL-008', name: 'TERSAN TERSANESİ' },
  { code: 'TRYAL-009', name: '1 NOLU DEMİR SAHASI' },
  { code: 'TRYAL-010', name: '2 NOLU DEMİR SAHASI' },
  { code: 'TRYAL-012', name: 'GİSAN ALTINOVA TERSANESİ' },
  { code: 'TRYAL-013', name: 'GİRGİN KALE TERSANESİ' },
  { code: 'TRYAL-014', name: 'GEMAK TERSANESİ' },
  { code: 'TRYAL-015', name: 'PARK TERSANESİ' },
  { code: 'TRYAL-016', name: 'DOĞRUYOL TERSANECİLİK' },
  { code: 'TRYAL-017', name: 'CEMRE TERSANESİ' },
  { code: 'TRYAL-018', name: 'ÇAKIRLAR TERSANESİ' },
  { code: 'TRYAL-019', name: 'BEŞİKTAŞ TERSANESİ' },
  { code: 'TRYAL-020', name: 'ARI TERSANESİ' },
  { code: 'TRYAL-021', name: 'ALTINOVA TERSANESİ' },
  { code: 'TRYAL-023', name: 'KAMER MARINE TERSANESİ' },
  { code: 'TRYAL-024', name: 'SEFİNE TERSANESİ' },
  { code: 'TRYAL-025', name: 'KUZEY STAR TERSANESİ' },
  { code: 'TRYAL-027', name: 'KARADENİZ HOLDİNG TERSANESİ' },
  { code: 'TRYAL-028', name: 'EROL ŞENKAYA TERSANESİ' },
  { code: 'TRYAL-029', name: 'AYKIN TERSANECİLİK' },
  { code: 'TRYAL-033', name: 'GÖK DENİZCİLİK YALOVA TAVŞANLI' },
  { code: 'TRYAL-034', name: 'HATSAN TERSANESİ' },
  { code: 'TRYAL-035', name: 'HİCRİ ERCİLİ TERSANECİLİK' },
  { code: 'TRYAL-036', name: 'TOPÇULAR ARABALI VAPUR İSKELESİ' },
  { code: 'TRYAL-037', name: 'YALOVA HIZLI FERİBOT İSKELESİ' },
  { code: 'TRYAL-038', name: 'ÇINARCIK BALIKÇI BARINAĞI' },
  { code: 'TRYAL-039', name: 'ESENKÖY BALIKÇI BARINAĞI' },
  { code: 'TRYAL-040', name: 'MERKEZ BALIKÇI BARINAĞI' },
  { code: 'TRYAL-041', name: 'YALOVA TEŞVİKİYE İSKELESİ' },
  { code: 'TRYAL-042', name: 'YALOVA KOCADERE İSKELESİ' },
  { code: 'TRYAL-043', name: 'ESENKÖY BALIKCI BARINAĞI' },
  { code: 'TRYAL-044', name: 'DEREAĞZI BALIKÇI BARINAĞI' },
  { code: 'TRYAL-045', name: 'YÜKSEL TERSANESİ' },
  { code: 'TRYAL-046', name: 'SELTAŞ TERSANESİ' },
  { code: 'TRYAL-047', name: 'ARİF KALKAVANOĞLU TERSANESİ' },
  { code: 'TRYAL-048', name: 'GÜRDESAN TERSANESİ' },
  { code: 'TRYAL-049', name: 'BOĞAZİÇİ TERSANESİ' },
  { code: 'TRYAL-050', name: 'HERÇELİK TERSANESİ' },
  { code: 'TRYAL-051', name: 'ICT YAT TERSANESİ' },
  { code: 'TRYAL-053', name: 'DEN-TA DENİZCİLİK TERSANESİ' },
  { code: 'TRYAL-054', name: 'İDO MERKEZ DENİZ OTOBÜSÜ İSKELESİ' },
  { code: 'TRYAL-055', name: 'KORUKÖY BALIKÇI BARINAĞI' },
  { code: 'TRYAL-056', name: 'CEMRE MÜHENDİSLİK TERSANESİ' },
  { code: 'TRYAL-057', name: 'HERSEK TERSANESİ' },
  { code: 'TRYAL-058', name: 'KARSAN TERSANESİ' },
  { code: 'TRYAL-059', name: 'İDO ÇINARCIK DENİZ OTOBÜSÜ İSKELESİ' },
  { code: 'TRYAL-060', name: 'ÖZATA DENİZCİLİK TERSANESİ' },
  { code: 'TRYAL-061', name: 'BİLGİN YATÇILIK TERSANESİ' },
  { code: 'TRYAL-062', name: 'TISG TURKEY YAT TERSANECİLİK A.Ş.' },
  { code: 'TRYAL-063', name: 'YALOVA GEMİ TERSANECİLİK' },
  { code: 'TRZON-001', name: 'EREN LİMANI' },
  { code: 'TRZON-002', name: 'TTK ZONGULDAK LİMANI' },
  { code: 'TRZON-003', name: 'FİLYOS LİMANI' },
  { code: 'TRZON-004', name: 'FİLYOS TÜRKİYE PETROLLERİ LİMANI' },
  { code: 'TRZON-005', name: '1-A DEMİR SAHASI' },
  { code: 'TRZON-006', name: '1-B DEMİR SAHASI' },
  { code: 'TRZON-007', name: '2-A DEMİR SAHASI' },
  { code: 'TRZON-008', name: '2-B DEMİR SAHASI' },
  { code: 'TRZON-009', name: '3-A DEMİR SAHASI' },
  { code: 'TRZON-010', name: '3-B DEMİR SAHASI' },
  { code: 'TR002-001', name: 'DEMİR SAHASI' },
  { code: 'TR002-002', name: 'BAĞIRGANLI BALIKÇI BARINAĞI' },
  { code: 'TR002-003', name: 'KEFKEN BALIKÇI BARINAĞI' },
  { code: 'TR003-001', name: 'DEMİR SAHASI' },
  { code: 'TR01M-001', name: 'SUGÖZÜ ENERJİ SANTRALİ İSKELESİ' },
  { code: 'TR01M-002', name: 'SANKO LİMAN TESİSİ' },
  { code: 'TR01M-003', name: 'BOTAŞ CEYHAN TERMİNALİ' },
  { code: 'TR01M-004', name: 'BTC HAYDAR ALİYEV DENİZ TERMİNALİ' },
  { code: 'TR01M-005', name: 'SÖNMEZ ÇİMENTO LİMAN TESİSİ' },
  { code: 'TR01M-006', name: 'AKDENİZ GEMİ İNŞA TERSANESİ' },
  { code: 'TR01M-007', name: 'TOROS TARIM CEYHAN TERMİNALİ' },
  { code: 'TR01M-008', name: 'EMBA LİMANI' },
  { code: 'TR01M-009', name: '1 NOLU  DEMİR SAHASI (TEHLİKELİ YÜK TAŞIYANLAR)' },
  { code: 'TR01M-010', name: '2 NOLU  DEMİR SAHASI' },
  { code: 'TR01M-011', name: '3 NOLU  DEMİR SAHASI' },
  { code: 'TR01M-012', name: '4 NOLU  DEMİR SAHASI' },
  { code: 'TR027-001', name: 'CİDE DEMİR BÖLGESİ' },
  { code: 'TR039-001', name: 'KARASU LİMANI' },
  { code: 'TR039-002', name: 'DEMİRLEME SAHASI' },
  { code: 'TR092-001', name: 'ANADOLU TERSANESİ' },
  { code: 'TR092-002', name: 'ARGEM TERSANECİLİK' },
  { code: 'TR092-003', name: 'ÇEKSAN TERSANESİ' },
  { code: 'TR092-005', name: 'ÇİNDEMİR TERSANESİ' },
  { code: 'TR092-006', name: 'DEARSAN TERSANESİ' },
  { code: 'TR092-007', name: 'DENİZ ENDÜSTRİSİ TERSANESİ' },
  { code: 'TR092-008', name: 'DENTAŞ TERSANESİ' },
  { code: 'TR092-009', name: 'DESAN TERSANESİ' },
  { code: 'TR092-010', name: 'DESAN TERSANESİ KÜÇÜK HAVUZ' },
  { code: 'TR092-011', name: 'GEMAK TERSANESİ' },
  { code: 'TR092-012', name: 'GEMDOK' },
  { code: 'TR092-013', name: 'GEMTİŞ TERSANESİ' },
  { code: 'TR092-014', name: 'GİSAN GEMİ İNŞA SANAYİ VE TİC' },
  { code: 'TR092-015', name: 'GİSAŞ RIHTIMI' },
  { code: 'TR092-016', name: 'HİDRODİNAMİK TERSANESİ' },
  { code: 'TR092-017', name: 'İSTANBUL TERSANESİ' },
  { code: 'TR092-019', name: 'PENDİK ASKERİ TERSANE' },
  { code: 'TR092-021', name: 'SEDEF GEMİ İNŞAA AŞ.' },
  { code: 'TR092-022', name: 'ADA TERSANESİ (2. TESİS)' },
  { code: 'TR092-024', name: 'ŞAHİN ÇELİK TERSANESİ' },
  { code: 'TR092-025', name: 'DENTAŞ TERSANESİ İSTANBUL ŞB.' },
  { code: 'TR092-026', name: 'TORLAK TERSANESİ' },
  { code: 'TR092-028', name: 'TUZLA DEMİR' },
  { code: 'TR092-029', name: 'TUZLA GEMİ END.TERSANESİ' },
  { code: 'TR092-030', name: 'TUZLA TERSANECİLİK VE TURİZM' },
  { code: 'TR092-031', name: 'TÜRKTER TERSANESİ' },
  { code: 'TR092-032', name: 'UN RO-RO PENDİK TERMİNALİ' },
  { code: 'TR092-033', name: 'YARDGEM TERSANESİ' },
  { code: 'TR092-034', name: 'ART GEMİ İNŞA VE TERSANECİLİK HİZMETLERİ A.Ş. (1. TESİS)' },
  { code: 'TR092-035', name: 'YILDIRIM TERSANESİ' },
  { code: 'TR092-036', name: 'TUZLA VİAPORT MARİNA' },
  { code: 'TR092-037', name: 'KARTAL KUMCULAR İSKELELERİ' },
  { code: 'TR092-038', name: 'ASTAŞ ASLAN TERSANECİLİK' },
  { code: 'TR092-039', name: 'ÇELİKTRANS TERSANESİ' },
  { code: 'TR092-040', name: 'AYKIN TERSANESİ' },
  { code: 'TR092-041', name: 'ARKADAŞ TEKNE İMAL' },
  { code: 'TR092-042', name: 'ADA TERSANESİ (1. TESİS)' },
  { code: 'TR092-043', name: 'YONCA ONUK TEKNE İMAL' },
  { code: 'TR092-044', name: 'YILDIZ TERSANESİ' },
  { code: 'TR092-045', name: 'URSA TERSANESİ' },
  { code: 'TR092-046', name: 'TUZLA İDO TERMİNALİ' },
  { code: 'TR092-047', name: 'TUZLA DLH LİMANI' },
  { code: 'TR092-048', name: 'TUZLA BELEDİYE İSKELESİ' },
  { code: 'TR092-049', name: 'TURQUOISE YAT' },
  { code: 'TR092-050', name: 'TERSAN TERSANESİ' },
  { code: 'TR092-051', name: 'SS YENİ TİC.TUR.DZ.ARÇ.YP.KOOP' },
  { code: 'TR092-052', name: 'SNR GEMİ İNŞA TERSANESİ' },
  { code: 'TR092-053', name: 'SELAHATTİN TELCİ TERSANESİ' },
  { code: 'TR092-054', name: 'SANMAR TERSANESİ' },
  { code: 'TR092-055', name: 'RMK MARINE TERSANESİ' },
  { code: 'TR092-056', name: 'PIRLANT YAT ÇEKEK' },
  { code: 'TR092-057', name: 'ANADOLU PORT' },
  { code: 'TR092-058', name: 'PENDİK İDO TERMİNALİ' },
  { code: 'TR092-059', name: 'ÖZKARADENİZ TERSANESİ' },
  { code: 'TR092-060', name: 'NESA TERSANESİ' },
  { code: 'TR092-061', name: 'KUZEY STAR TERSANESİ' },
  { code: 'TR092-062', name: 'KPT TERSANESİ' },
  { code: 'TR092-063', name: 'KARTAL İDO TERMİNALİ' },
  { code: 'TR092-064', name: 'KARTAL DEMİR YERİ' },
  { code: 'TR092-065', name: 'İSTANBUL DZ. GEMİ İNŞ.TERSANESİ' },
  { code: 'TR092-066', name: 'ART GEMİ İNŞA VE TERSANECİLİK HİZMETLERİ A.Ş. (2. TESİS)' },
  { code: 'TR092-067', name: 'ENGİN DENİZCİLİK İŞLETMESİ SAN' },
  { code: 'TR092-068', name: 'ENGİN DENİZCİLİK TERSANESİ' },
  { code: 'TR092-069', name: 'ERKAL TERSANESİ' },
  { code: 'TR092-070', name: 'PENDİK MARİNTÜRK MARİNA' },
  { code: 'TR092-071', name: 'Tuzlaport Tersanesi' },
];

export function searchPorts(query: string): Port[] {
  if (!query || query.length < 2) return TURKEY_PORTS.slice(0, 50);
  const q = query.toUpperCase();
  return TURKEY_PORTS.filter(p => p.name.includes(q) || p.code.includes(q)).slice(0, 50);
}